(() => {
 const reduced=matchMedia('(prefers-reduced-motion: reduce)');
 window.steelMotion={paused:reduced.matches};
 document.documentElement.classList.add('js');
 const reveals=document.querySelectorAll('.reveal');
 const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});
 reveals.forEach(e=>observer.observe(e));
 const motionButtons=document.querySelectorAll('.motion-toggle');
 function setMotion(value){window.steelMotion.paused=value;document.body.classList.toggle('paused',value);motionButtons.forEach(b=>{b.setAttribute('aria-pressed',String(value));b.setAttribute('aria-label',value?'Resume motion':'Pause motion');b.textContent=b.closest('.slider-controls')?(value?'▶':'Ⅱ'):(value?'Resume motion ▶':'Pause motion Ⅱ')});window.dispatchEvent(new Event('motionchange'))}
 motionButtons.forEach(b=>b.addEventListener('click',()=>setMotion(!window.steelMotion.paused)));
 reduced.addEventListener('change',e=>setMotion(e.matches));setMotion(reduced.matches);
 const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('nav');
 menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',open);nav.classList.toggle('open',open)});
 document.addEventListener('keydown',e=>{if(e.key==='Escape'){nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}});
 nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false')}));
 window.addEventListener('scroll',()=>document.querySelector('header').classList.toggle('scrolled',scrollY>30),{passive:true});
 const slides=[{title:'STEEL.<br>SOURCED WITH<br><em>PURPOSE.</em>',description:'Bringing buyers and suppliers together.<br>Making your next steel requirement a clearer conversation.',model:'beam'}, {title:'EVERY FORM.<br>THE RIGHT<br><em>CONNECTION.</em>',description:'Coils, sections, bars and pipes.<br>Start with your specification. Explore the possibilities.',model:'coil'}, {title:'YOUR NEED.<br>A CLEARER<br><em>WAY FORWARD.</em>',description:'From the first requirement to commercial coordination.<br>Keep the details aligned at every step.',model:'pipes'}];
 let current=0,slideTimer;
 function resetTimer(){clearInterval(slideTimer);slideTimer=setInterval(()=>{if(!window.steelMotion.paused&&!document.hidden)showSlide(current+1)},8000)}
 function showSlide(index){current=(index+slides.length)%slides.length;const s=slides[current];const title=document.querySelector('#hero-title');if(!title)return;title.innerHTML=s.title;document.querySelector('#hero-description').innerHTML=s.description;document.querySelector('#slide-count').textContent=`0${current+1} / 03`;title.classList.remove('changing');void title.offsetWidth;title.classList.add('changing');window.dispatchEvent(new CustomEvent('steelmodel',{detail:s.model}));const bar=document.querySelector('.hero-progress span');bar.style.animation='none';void bar.offsetWidth;bar.style.animation='';resetTimer()}
 if(document.querySelector('#hero-title')){document.querySelector('#slide-prev').addEventListener('click',()=>showSlide(current-1));document.querySelector('#slide-next').addEventListener('click',()=>showSlide(current+1));resetTimer()}
 const products={flat:{model:'coil',title:'Flat steel.',kicker:'01 / FLAT PRODUCTS',description:'Sheets, plates and coils for material requirements defined by grade, thickness and finish.',specs:['Grade and surface finish','Thickness, width and length','Quantity or coil weight','Delivery destination and timeline']},structural:{model:'beam',title:'Structural steel.',kicker:'02 / STRUCTURAL SECTIONS',description:'Beams, channels and angles for structural applications, sourced against the required section and grade.',specs:['Section type and dimensions','Material grade or applicable standard','Lengths and quantities for each item','Delivery destination and timeline']},bars:{model:'bars',title:'Bars & reinforcement.',kicker:'03 / LONG PRODUCTS',description:'Round bars and reinforcement products, with requirements defined by diameter, grade and length.',specs:['Bar type and diameter','Required grade or standard','Length, quantity and tonnage','Delivery destination and timeline']},pipes:{model:'pipes',title:'Pipes & sections.',kicker:'04 / HOLLOW SECTIONS',description:'Round pipes and hollow sections for requirements defined by outside dimensions and wall thickness.',specs:['Round, square or rectangular section','Outside dimensions and wall thickness','Grade, end use and quantity','Delivery destination and timeline']}};
 const tabs=[...document.querySelectorAll('[data-product]')];
 function selectProduct(key,hash=true){const p=products[key];if(!p||!tabs.length)return;tabs.forEach(t=>{const active=t.dataset.product===key;t.setAttribute('aria-selected',active);t.tabIndex=active?0:-1});document.querySelector('#product-panel').setAttribute('aria-labelledby',`tab-${key}`);document.querySelector('#product-title').textContent=p.title;document.querySelector('#product-kicker').textContent=p.kicker;document.querySelector('#product-description').textContent=p.description;document.querySelector('#product-specs').replaceChildren(...p.specs.map(s=>{const li=document.createElement('li');li.textContent=s;return li}));window.dispatchEvent(new CustomEvent('steelmodel',{detail:p.model}));document.querySelector('.steel-stage').dataset.model=p.model;if(hash)history.replaceState(null,'','#'+key)}
 tabs.forEach((t,i)=>{t.addEventListener('click',()=>selectProduct(t.dataset.product));t.addEventListener('keydown',e=>{let next;if(e.key==='ArrowRight')next=(i+1)%tabs.length;else if(e.key==='ArrowLeft')next=(i-1+tabs.length)%tabs.length;else if(e.key==='Home')next=0;else if(e.key==='End')next=tabs.length-1;else return;e.preventDefault();tabs[next].focus();selectProduct(tabs[next].dataset.product)})});
 if(tabs.length)selectProduct(location.hash.slice(1)||'flat',false);
 window.addEventListener('hashchange',()=>selectProduct(location.hash.slice(1),false));
 const form=document.querySelector('#enquiry-form');let brief='';
 if(form){form.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(form);brief=`STEEL SOURCING ENQUIRY\n\nName: ${d.get('name')}\nCompany: ${d.get('company')||'Not specified'}\nProduct: ${d.get('product')}\nQuantity: ${d.get('quantity')}\nSpecification: ${d.get('specification')}\nDelivery location: ${d.get('location')}\nRequired by: ${d.get('timeline')||'To be discussed'}\n\nPlease confirm availability and commercial terms.`;document.querySelector('#brief-text').textContent=brief;document.querySelector('#brief-result').hidden=false;document.querySelector('#brief-status').textContent='Your brief is ready. No enquiry has been sent.';document.querySelector('#brief-result').scrollIntoView({behavior:window.steelMotion.paused?'instant':'smooth',block:'nearest'})});document.querySelector('#copy-brief').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(brief);document.querySelector('#brief-status').textContent='Brief copied. Ready to share.'}catch{document.querySelector('#brief-status').textContent='Copy is unavailable. Use Download brief instead.'}});document.querySelector('#download-brief').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([brief],{type:'text/plain'}));const a=document.createElement('a');a.href=url;a.download='steel-sourcing-enquiry.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);document.querySelector('#brief-status').textContent='Your brief has been downloaded.'})}
})();
